library/urls.py
from django.urls import path
from . import views


app_name = 'library'

urlpatterns = [
    path('', views.mysite_home, name='mysite_home'),
    path('library_home/', views.library_home, name='library_home'),
    path('library_home/form/', views.form, name='form'),
    path('library_home/customers/', views.customers, name='customers'),
    path('library_home/customers/<int:customer_id>/', views.customer_ditails, name='customer_ditails'),
    path('library_home/shop/', views.Shop.as_view(), name='shop'),
    path('library_home/login', views.log_in, name='login'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('library.urls')),
    path('admin/', admin.site.urls),
    
    
]
urlpatterns += staticfiles_urlpatterns()

library/models.py
from django.db import models
from datetime import *


class Customer(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    date_of_birth = models.DateField(max_length=50)
    favorite_color = models.CharField(max_length=50, default='None')
    profile_picture = models.FileField(max_length=50, default='None')
    gender = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    email = models.EmailField(max_length=50)
    password = models.CharField(max_length=50)
    validation_question = models.CharField(max_length=50)
    answer = models.CharField(max_length=50, default='None')
    comment = models.CharField(max_length=100, default='None')

    def __str__(self) -> str:
        return Customer.first_name, Customer.last_name


class Book(models.Model):
    name = models.CharField(max_length=20, default='None')
    author = models.CharField(max_length=20, default='None')
    publish_date = models.DateField('date published')
    book_type = models.CharField(max_length=20, default='1')

    def __str__(self) -> str:
        return Book.name


class Loan(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    loan_date = models.DateField('The day the loan starts')
    return_date = models.DateField('Book return_date')

    def __str__(self) -> str:
        return Loan.book


# books_choices = ((1, "book1"), (2, "bbo2"))


# class Shop(models.Model):
#     book_name = models.CharField(books_choices, label="book"),
#     amount = models.CharField(label="amount"),

#     def __str__(self) -> str:
#         return Shop.book_name

books_choices = ((1, "book1"), (2, "bbo2"))


class Shop(models.Model):
    book_name = models.CharField(1),
    amount = models.CharField(),

    def __str__(self) -> str:
        return Shop.book_name

library/forms.py
from django import forms
from django.forms import ModelForm
from library.models import Customer,Shop


class CustomerForm(ModelForm):

    class Meta:
        model = Customer
        fields = "__all__"
        

# books_choices=((1, "book1"),(2, "bbo2"))
# class ShopForm(forms.Form):
#     book_name = forms.MultipleChoiceField(books_choices, label="book"),
#     amount = forms.ChoiceField(label="amount")
class ShopForm(forms.Form):
    book_name = forms.MultipleChoiceField(),
    amount = forms.ChoiceField()
    

library/views.py
from . models import Customer
from django.shortcuts import render, get_list_or_404
from django.http import HttpResponse, HttpResponsePermanentRedirect
from library.forms import CustomerForm, ShopForm
from django.urls import reverse
from django.views import View, generic
from django.contrib.auth import login


def mysite_home(request):
    return render(request, 'library/mysite_home.html')


def library_home(request):
    return render(request, 'library/library_home.html')


def form(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        for field in form.fields:
            form.fields[field].required = False
        if form.is_valid():
            form.save()
            return render(request, 'library/registration.html', {'form': CustomerForm})
        else:
            print(form.errors.as_text())
            return HttpResponsePermanentRedirect(reverse('library:library_home'))
    else:
        context = {"form": CustomerForm}
        return render(request, 'library/registration.html', context)


def log_in(request):
    # login(request, user)
    return HttpResponsePermanentRedirect('library/login.html')


def customers(request):
    all_customers = Customer.objects.all()
    context = {"all_customers": all_customers}
    return render(request, 'library/customers.html', context=context)


def customer_ditails(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)
    context = {"customer": customer}
    return render(request, 'library/customer_ditails.html', context=context)


class Shop(View):

    def post(self, request):
        form = ShopForm(request.POST)
        if form.is_valid():
            book_name = form.cleaned_data['book_name']
            amount = form.cleaned_data['amount']
            # c=Customer(book_name, amount)
            # c.save()
            Customer.objects.create(book_name=book_name, amount=amount)
            return HttpResponsePermanentRedirect(reverse('library:library_home'))
        else:
            message = 'error'
            return render(request, 'library:library_home')

    def get(self, request):
        form = ShopForm()
        context = {'form': form}
        return render(request, 'library/shop.html', context=context)


# class customer2(generic.ListView):
#     template_name = "ibrary/customers.html"
#     context_object_name = "all_customers"

#     def get_queryset(self):
#         return Customer.objects.all()


# class customers2(generic.ListView):
#     model = Customer
#     template_name = "ibrary/customer.html"

library/templates/library/customer_ditails.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="{% static 'library/customer_ditails.css' %}">
    <title>Document</title>
</head>

<body>
    {%if customer%}
    <input type="image" ; name="Profile Picture " ; id="Profile Picture" ; tabindex="1" ; title="Profile Picture" ;
        alt="Profile Picture" ; width="100" height="100" ; src="" />
    <table>
        <caption>{{customer.first_name}} {{customer.last_name}}</caption>
        <tr>
            <td class="x">First name:</td>
            <td class="y">{{customer.first_name}}</td>
        </tr><br />
        <tr>
            <td class="x">Last name:</td>
            <td class="y">{{customer.last_name}}</td>
        </tr><br />
        <tr>
            <td class="x">City:</td>
            <td class="y">{{customer.city}}</td>
        </tr><br />
        <tr>
            <td class="x">Country:</td>
            <td class="y">{{customer.country}}</td>
        </tr><br />
        <tr>
            <td class="x">Date Of Birth:</td>
            <td class="y">{{customer.date_of_birth}}</td>
        </tr><br />
        <tr>
            <td class="x">Gender:</td>
            <td class="y">{{customer.gender}}</td>
        </tr><br />
        <tr>
            <td class="x">Phone:</td>
            <td class="y">{{customer.phone}}</td>
        </tr><br />
        <tr>
            <td class="x">Email:</td>
            <td class="y">{{customer.email}}</td>
        </tr><br />
    </table>
    {%else%}
    <p>No Customers found</p>
    {%endif%}
</body>

</html>

library/templates/library/customers.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="{% static 'library/customers.css' %}">
    <title>Document</title>
</head>

<body>
    {%if all_customers%}
    <table>
        <caption> Customers</caption>
        {%for customer in all_customers%}
        <tr>
            <td class="x">{{customer.id}}</td>
            <td><a class="y" href="{% url 'library:customer_ditails' customer.id %}">{{customer.first_name}}
                    {{customer.last_name}}</a></td>
        </tr><br />
        {%endfor%}

        {%else%}
        <p>No Customers found</p>
        {%endif%}
    </table>
</body>

</html>

library/templates/library/library_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="{% static 'library/library_home.css' %}">
    <title>Document</title>
</head>

<body>
    <video autoplay muted loop id="LibraryVideo">
        <source src="../static/library/images/LibraryVideo.mp4" type="video/mp4">
      </video>
    <h1>Welcome To The Library</h1>
    <div>
        <a href="{% url 'library:customers' %}" ; id="Customers" ; name="Customers" ; tabindex="1" ; title="Customers">Customers</a>
        <a href="{% url 'library:form' %}" ; id="Registration" ; name="Registration" ; tabindex="2" ; title="Registration">Registration</a>
        <a href="{% url 'library:shop' %}" ; id="Shop" ; name="Shop" ; tabindex="2" ; title="Shop">Shop</a>
    </div>
</body>

</html>

library/templates/library/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="{% static 'library/mysite_home.css' %}">
    <title>Document</title>
</head>

<body>
    <video autoplay muted loop id="BackgroundVideo">
        <source src="../static/library/images/BackgroundVideo.mp4  " type="video/mp4">
      </video>
      
    <h1>Welcome To MySite</h1>
    <div>
        <a href="{% url 'library:library_home' %}" ; name="Library" ; id="Library"; tabindex="1" ; title="Library">Library</a>
    </div>
</body>

</html>

library/templates/library/mysite_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="{% static 'library/mysite_home.css' %}">
    <title>Document</title>
</head>

<body>
    <video autoplay muted loop id="BackgroundVideo">
        <source src="../static/library/images/BackgroundVideo.mp4  " type="video/mp4">
      </video>
      
    <h1>Welcome To MySite</h1>
    <div>
        <a href="{% url 'library:library_home' %}" ; name="Library" ; id="Library"; tabindex="1" ; title="Library">Library</a>
    </div>
</body>

</html>

library/templates/library/registration.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="{% static 'library/registration.css' %}">
    <title>New customer registration form</title>
</head>

<body>
    <p id="sale">New sale!<br /> A gift book for the first 100 registrants</p>
    <form action="{% url 'library:form' %}" ; method="post">
        {% csrf_token %}
        <div>
            <h1>Registration Form</h1>
            <p>Welcome to the registration page</p>
            <p> here you can create a user and join us :)</p><br /><br />
            <input type="button" ; name="Help" ; id="1" ; tabindex="1" ; title="Help" ; value="Help" ;
                onclick="alert('To create a user, fill out the registration form, Enter your personal details in the form.')" />
        </div>

        <fieldset>
            <legend>Personal Details</legend>
            <label for="first_name">First Name:</label>
            <input type="Text" ; name="first_name" ; id="1" ; tabindex="1" ; title="First Name" ; size="20" ;
                maxlength="20" ; placeholder="Enter First Name" ; required /><br /><br />
            <label for="last_name">Last Name:</label>
            <input type="Text" ; name="last_name" ; id="2" ; tabindex="2" ; title="Last Name" ; size="20" ;
                maxlength="20" ; placeholder="Enter Last Name" ; required />
        </fieldset>

        <fieldset>
            <legend>Residential Details</legend>
            <label for="city">City:</label>
            <input type="Text" ; name="city" ; id="3" ; tabindex="3" ; title="City" ; size="20" ; maxlength="20" ;
                placeholder="Enter City" ; required /><br /><br />
            <label for="country">Country:</label>
            <input type="Text" ; name="country" ; id="4" ; tabindex="4" ; title="Country" ; size="20" ; maxlength="20" ;
                placeholder="Enter Country" ; required /><br /><br />
            <label for="date_of_birth">Date Of Birth:</label>
            <input type="Date" ; name="date_of_birth" ; id="6" ; tabindex="6" ; title="Date" ; required /><br /><br />

            <label for="favorite_color">Favorite Color:</label>
            <input type="Color" ; name="favorite_color" ; id="Favorite Color" ; tabindex="5" ; title="Favorite Color" ;
                list="Colors" />
            <datalist id="Colors">
                <option value="#FF0000"></option>
                <option value="#FB00FF"></option>
                <option value="#FF00AE"></option>
                <option value="#FBFF00"></option>
                <option value="#00FFEE"></option>
                <option value="#37FF00"></option>
                <option value="#001EFF"></option>
                <option value="#FFAE00"></option>
                <option value="#000000"></option>
                <option value="#FFFFFF"></option>
            </datalist><br /><br />
            <label for="profile_picture">Profile Picture</label>
            <input type="file" ; name="profile_picture" ; id="1" ; tabindex="1" ; title="Profile Picture" /><br /><br />
        </fieldset>

        <fieldset>
            <legend>Gender</legend>
            Mr.<input type="Radio" ; name="gender" ; id="7" ; tabindex="7" ; value="Mr" ; title="Mr" ; required />
            Mrs.<input type="Radio" ; name="gender" ; id="8" ; tabindex="6" ; value="Mrs" ;title="Mrs" ; required />
            Other<input type="Radio" ; name="gender" ; id="8" ; tabindex="6" ; value="Other" ;title="Other" ;
                required />
        </fieldset>

        <fieldset>
            <legend>Communication Details</legend>
            <label for="phone">Phone:</label>
            <input type="tel" ; name="phone" ; id="10" ; tabindex="10" ; title="Phone" ; size="20" ; maxlength="20" ;
                placeholder="Enter Phone" ; required /><br /><br />
            <label for="email">Email:</label>
            <input type="email" ; name="email" ; id="9" ; tabindex="9" ; title="Email" ; size="20" ; maxlength="50" ;
                placeholder="Enter Email" ; required />
        </fieldset>

        <fieldset>
            <legend>Password</legend>
            <label for="password">New Password</label><br>
            <input type="Password" ; name="password" ; id="7" ; tabindex="7" ; title="New Password" ; size="20" ;
                maxlength="20" ; placeholder="Enter New Password" ; /><br /><br />
            <label for="confirm_password">Confirm Password</label><br>
            <input type="Password" ; name="confirm_password" ; id="8" ; tabindex="8" ; title="Confirm password" ;
                size="20" ; maxlength="20" ; placeholder="Confirm password" ; /><br /><br />
            <label for="validation_question">Choose a Validation Question</label><br />

            <select name="validation_question" ; id="" title="Validation Question">
                <option value="" ; selected="selected"></option>
                <option value="">What is the name of your first girlfriend?</option>
                <option value="">What is the name of your elementry school?</option>
                <option value="">What is the previous last name of your mom?</option>
            </select><br /><br />

            <label for="answer">Answer</label><br />
            <input type="Text" ; name="answer" ; id="1" ; tabindex="1" ; title="Answer" ; size="30" ; maxlength="30" ;
                placeholder="Enter Answer" />
        </fieldset>

        <fieldset>
            <legend>Sending</legend>
            <textarea name="comment" ; id="8" ; tabindex="8" ; title="Comment" ; maxlength="100" ; placeholder="Comment"
                ; cols="30" ; rows="3"></textarea><br />

            <div id="Terms">
                <input type="checkbox" ; name="Advertisements" ; id="Terms" ; tabindex="2" ; title="Advertisements" ;
                    checked="checked" ; disabled="disabled" />I agree to receive advertisements<br /><br />
                <input type="checkbox" ; name="Regulations" ; id="Terms" ; tabindex="2" ; title="Regulations" />I
                have read and agree to the terms <br /><br />
            </div>
            <input type="image" ; name="Reset" ; id="Reset" ; tabindex="8" ; title="Reset" ; alt="Reset" ; width="100"
                height="50" ; src='{% static "../static/library/images/reset.jpg" %}' ;
                onclick="alert('Start again')" />
            <input type="image" ; name="Submit " ; id="Submit" ; tabindex="8" ; title="Submit" ; alt="Submit" ;
                width="100" height="100" ; src='{% static "../static/library/images/submit.png" %}' ;
                onclick="alert('The form has been sent successfully !')" />
        </fieldset>
    </form>
</body>

</html>

library/templates/library/shop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'library:shop' %}" ; method="post">
    {% csrf_token %}
    <h1>Books</h1>
    <h1>sale!!!!</h1>
        
    {{form.book_name}}
    {{amount}}
    
</form>
</body>
</html>